apiVersion: v1
kind: ConfigMap

metadata:
  name: rag-config
  namespace: rag-app

data:
  LLM_PROVIDER: "openai"
  LLM_MODEL: "gpt-4o-mini"
  LLM_TEMPERATURE: "0.3"
  PLANNER_MODEL: "gpt-4.1-nano"

  EMBEDDING_MODEL: "text-embedding-3-small"
  EMBEDDING_BATCH_SIZE: "100"

  CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"

  QDRANT_HOST: "qdrant"
  QDRANT_PORT: "6333"
  QDRANT_COLLECTION: "rag"
  VECTOR_SIZE: "1536"

  POSTGRES_DB: "ragdb"

  API_BASE_URL: "http://rag-api:8000"

  LANGSMITH_TRACING: "true"

  HOST: "0.0.0.0"
  PORT: "8000"