apiVersion: v1
kind: Secret

metadata:
  name: rag-secret
  namespace: rag-app

type: Opaque

stringData:
  OPENAI_API_KEY: "REPLACE_OPENAI_API_KEY"

  TAVILY_API_KEY: "REPLACE_TAVILY_API_KEY"

  LANGSMITH_API_KEY: "REPLACE_LANGSMITH_API_KEY"
  LANGSMITH_PROJECT: "REPLACE_LANGSMITH_PROJECT"

  POSTGRES_USER: "REPLACE_POSTGRES_USER"
  POSTGRES_PASSWORD: "REPLACE_POSTGRES_PASSWORD"

  DATABASE_URL: "REPLACE_DATABASE_URL"