apiVersion: v1
kind: Service

metadata:
  name: rag-streamlit
  namespace: rag-app

spec:
  selector:
    app: rag-streamlit

  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501

  type: ClusterIP